
#
# Elide: Docker Images
# --------------------
# Image: JVM (v22)
#

IMAGE ?= runtime/jvm22
PROVENANCE ?= yes
PUB_IMAGE ?= runtime-jvm22
REPOSITORY ?= tools/$(IMAGE)
PUB_IMAGE_PATH ?= ghcr.io/elide-dev/runtime/jvm22:$(VERSION)
ORIGIN_IMAGE ?= $(PUB_IMAGE_PATH)

include ../Docker.mk
