/*
 * Copyright (c) 2024-2025 Elide Technologies, Inc.
 *
 * Licensed under the MIT license (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 *   https://opensource.org/license/mit/
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under the License.
 */
package elide.runtime.localai

import elide.runtime.localai.NativeLocalAi.infer

/**
 * ## Inference Chunk Callback
 *
 * Callback type which is used to consume chunks of generated inference output. An object of this type is defined by
 * the engine or developer, and is called from the native inference layer (via JNI) as inference output is generated
 * from background threads.
 *
 * See [infer] for more information.
 */
@FunctionalInterface public fun interface InferenceChunkCallback {
  /**
   * Receive a chunk of generated output from an inference operation.
   *
   * This method is called from the native layer, so it must be available for use via reflection and JNI.
   *
   * @param chunk The chunk of output generated by the inference operation.
   */
  public fun onChunk(chunk: String)
}
