codecov:
  require_ci_to_pass: true
  bot: "elidebot"
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "25...40"
  status:
    project:
      default:
        informational: true
    patch: off

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

parsers:
  javascript:
    enable_partials: yes
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

github_checks:
  annotations: true

ignore:
  - "samples"
  - "tools/processor"
  - "tools/substrate/injekt"
  - "tools/substrate/sekret"
  - "tools/substrate/interakt"
  - "tools/substrate/compiler-util"
  - "tools/plugin/gradle-plugin"
  - "packages/proto/proto-flatbuffers"
  - "packages/proto/proto-test"
  - "packages/graalvm/src/main/kotlin/elide/runtime/feature"
  - "tools"
  - "samples"
  - "**/*Feature.java"
  - "**/*Feature.kt"
  - "packages/model/src/jvmMain/kotlin/kotlinx/serialization/protobuf/schema/ProtoBufSchemaGeneratorImpl.kt"
  - "packages/proto/proto-core"
  - "packages/proto/proto-core/src/main/**/*.*"
  - "packages/proto/proto-protobuf"
  - "packages/proto/proto-protobuf/src/main/**/*.*"
  - "packages/proto/proto-kotlinx"
  - "packages/proto/proto-kotlinx/src/main/**/*.*"
  - "packages/proto/proto-capnp"
  - "packages/proto/proto-capnp/src/main/**/*.*"
  - "packages/cli/src/main/kotlin/elide/tool/engine/*.*"
  - "packages/cli/src/main/kotlin/elide/tool/engine/**/*.*"
  - "packages/model/src/jvmMain/kotlin/kotlinx/**/*.*"
  - "packages/cli/src/main/kotlin/elide/tool/cli/output/Mosaic.kt"
  - "packages/cli/src/main/kotlin/elide/tool/engine/NativeUtil.kt"
  - "packages/cli/src/main/kotlin/elide/tool/testing/TestContext.kt"
  - "packages/*/src/commonMain/**/*.*"
  - "packages/runtime/**/*.*"
  - "packages/transport/**/*.*"
  - "packages/sqlite/**/*.*"
  - "packages/rpc/**/*.*"
  - "packages/model/**/*.*"
  - "packages/graalvm-rb/**/*.*"
  - "packages/graalvm-wasm/**/*.*"
  - "packages/cli-bridge/**/*.*"
  - "packages/graalvm-ts/src/main/java/elide/runtime/lang/typescript/TypeScriptModuleLoader.java"
  - "packages/graalvm-ts/src/main/java/elide/runtime/lang/typescript/TypeScriptFileTypeDetector.java"
