codecov:
  require_ci_to_pass: true
  bot: "elidebot"
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "25...40"
  status:
    project:
      default:
        informational: true
    patch: off

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

parsers:
  javascript:
    enable_partials: yes
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

github_checks:
  annotations: true

ignore:
  - "samples"
  - "tools/processor"
  - "tools/substrate/injekt"
  - "tools/substrate/sekret"
  - "tools/substrate/interakt"
  - "tools/substrate/kotlin-compiler-util"
  - "tools/plugin/gradle-plugin"
  - "packages/proto/proto-flatbuffers"
  - "packages/graalvm/src/main/kotlin/elide/runtime/feature"
