base: &base
  - ".version"
  - ".release"

devcontainer: &devcontainer
  - *base
  - ".devcontainer/*.*"
  - ".devcontainer/**/*.*"

model: &model
  - *base
  - "proto/**/*.*"

packages: &packages
  - *base
  - *model
  - "packages"
  - "packages/*"
  - "packages/**/*.*"

tools: &tools
  - *base
  - "tools"
  - "tools/*"
  - "tools/**/*.*"

images: &images
  - *base
  - "tools/images/*"
  - "tools/images/*.*"
  - "tools/images/**/*.*"

critical_workflows: &critical_workflows
  - ".github/workflows/ci.build.yml"
  - ".github/workflows/ci.test.yml"
  - ".github/workflows/on.pr.yml"
  - ".github/workflows/on.push.yml"

workflows: &workflows
  - ".github/workflows/*.yml"

srcs: &srcs
  - *base
  - *model
  - *packages
  - *tools
  - *critical_workflows

natives: &natives
  - *base
  - "crates"
  - "crates/*"
  - "crates/**/*.*"
  - "third_party/Makefile"
  - "third_party/*/**/*.*"

any: &any
  - *base
  - *devcontainer
  - *model
  - *packages
  - *tools
  - *images
  - *critical_workflows
  - *workflows
  - *srcs
  - *natives
