// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: elide/meta/app.proto

package tools.elide.meta;

/**
 * <pre>
 * Info regarding an Elide application.
 * </pre>
 *
 * Protobuf type {@code meta.AppInfo}
 */
public final class AppInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:meta.AppInfo)
    AppInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AppInfo.newBuilder() to construct.
  private AppInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AppInfo() {
    version_ = "";
    name_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AppInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AppInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            version_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            name_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              endpoints_ = com.google.protobuf.MapField.newMapField(
                  EndpointsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<java.lang.String, tools.elide.meta.Endpoint>
            endpoints__ = input.readMessage(
                EndpointsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            endpoints_.getMutableMap().put(
                endpoints__.getKey(), endpoints__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return tools.elide.meta.App.internal_static_meta_AppInfo_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 3:
        return internalGetEndpoints();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return tools.elide.meta.App.internal_static_meta_AppInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            tools.elide.meta.AppInfo.class, tools.elide.meta.AppInfo.Builder.class);
  }

  private int bitField0_;
  public static final int VERSION_FIELD_NUMBER = 1;
  private volatile java.lang.Object version_;
  /**
   * <pre>
   * Version string of the application.
   * </pre>
   *
   * <code>string version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public java.lang.String getVersion() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      version_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Version string of the application.
   * </pre>
   *
   * <code>string version = 1;</code>
   * @return The bytes for version.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVersionBytes() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   * Name of the application, if known.
   * </pre>
   *
   * <code>optional string name = 2;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Name of the application, if known.
   * </pre>
   *
   * <code>optional string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Name of the application, if known.
   * </pre>
   *
   * <code>optional string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENDPOINTS_FIELD_NUMBER = 3;
  private static final class EndpointsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, tools.elide.meta.Endpoint> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, tools.elide.meta.Endpoint>newDefaultInstance(
                tools.elide.meta.App.internal_static_meta_AppInfo_EndpointsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                tools.elide.meta.Endpoint.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, tools.elide.meta.Endpoint> endpoints_;
  private com.google.protobuf.MapField<java.lang.String, tools.elide.meta.Endpoint>
  internalGetEndpoints() {
    if (endpoints_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          EndpointsDefaultEntryHolder.defaultEntry);
    }
    return endpoints_;
  }

  public int getEndpointsCount() {
    return internalGetEndpoints().getMap().size();
  }
  /**
   * <pre>
   * Map of endpoint tags to their info payloads for this application.
   * </pre>
   *
   * <code>map&lt;string, .meta.Endpoint&gt; endpoints = 3;</code>
   */

  @java.lang.Override
  public boolean containsEndpoints(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetEndpoints().getMap().containsKey(key);
  }
  /**
   * Use {@link #getEndpointsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, tools.elide.meta.Endpoint> getEndpoints() {
    return getEndpointsMap();
  }
  /**
   * <pre>
   * Map of endpoint tags to their info payloads for this application.
   * </pre>
   *
   * <code>map&lt;string, .meta.Endpoint&gt; endpoints = 3;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, tools.elide.meta.Endpoint> getEndpointsMap() {
    return internalGetEndpoints().getMap();
  }
  /**
   * <pre>
   * Map of endpoint tags to their info payloads for this application.
   * </pre>
   *
   * <code>map&lt;string, .meta.Endpoint&gt; endpoints = 3;</code>
   */
  @java.lang.Override

  public tools.elide.meta.Endpoint getEndpointsOrDefault(
      java.lang.String key,
      tools.elide.meta.Endpoint defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, tools.elide.meta.Endpoint> map =
        internalGetEndpoints().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * Map of endpoint tags to their info payloads for this application.
   * </pre>
   *
   * <code>map&lt;string, .meta.Endpoint&gt; endpoints = 3;</code>
   */
  @java.lang.Override

  public tools.elide.meta.Endpoint getEndpointsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, tools.elide.meta.Endpoint> map =
        internalGetEndpoints().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(version_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, version_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetEndpoints(),
        EndpointsDefaultEntryHolder.defaultEntry,
        3);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(version_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, version_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    for (java.util.Map.Entry<java.lang.String, tools.elide.meta.Endpoint> entry
         : internalGetEndpoints().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, tools.elide.meta.Endpoint>
      endpoints__ = EndpointsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, endpoints__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof tools.elide.meta.AppInfo)) {
      return super.equals(obj);
    }
    tools.elide.meta.AppInfo other = (tools.elide.meta.AppInfo) obj;

    if (!getVersion()
        .equals(other.getVersion())) return false;
    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (!internalGetEndpoints().equals(
        other.internalGetEndpoints())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion().hashCode();
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (!internalGetEndpoints().getMap().isEmpty()) {
      hash = (37 * hash) + ENDPOINTS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetEndpoints().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static tools.elide.meta.AppInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tools.elide.meta.AppInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tools.elide.meta.AppInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tools.elide.meta.AppInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tools.elide.meta.AppInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tools.elide.meta.AppInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tools.elide.meta.AppInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static tools.elide.meta.AppInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static tools.elide.meta.AppInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static tools.elide.meta.AppInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static tools.elide.meta.AppInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static tools.elide.meta.AppInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(tools.elide.meta.AppInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Info regarding an Elide application.
   * </pre>
   *
   * Protobuf type {@code meta.AppInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:meta.AppInfo)
      tools.elide.meta.AppInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tools.elide.meta.App.internal_static_meta_AppInfo_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetEndpoints();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMutableEndpoints();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tools.elide.meta.App.internal_static_meta_AppInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tools.elide.meta.AppInfo.class, tools.elide.meta.AppInfo.Builder.class);
    }

    // Construct using tools.elide.meta.AppInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      version_ = "";

      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableEndpoints().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return tools.elide.meta.App.internal_static_meta_AppInfo_descriptor;
    }

    @java.lang.Override
    public tools.elide.meta.AppInfo getDefaultInstanceForType() {
      return tools.elide.meta.AppInfo.getDefaultInstance();
    }

    @java.lang.Override
    public tools.elide.meta.AppInfo build() {
      tools.elide.meta.AppInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public tools.elide.meta.AppInfo buildPartial() {
      tools.elide.meta.AppInfo result = new tools.elide.meta.AppInfo(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.version_ = version_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.name_ = name_;
      result.endpoints_ = internalGetEndpoints();
      result.endpoints_.makeImmutable();
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof tools.elide.meta.AppInfo) {
        return mergeFrom((tools.elide.meta.AppInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(tools.elide.meta.AppInfo other) {
      if (other == tools.elide.meta.AppInfo.getDefaultInstance()) return this;
      if (!other.getVersion().isEmpty()) {
        version_ = other.version_;
        onChanged();
      }
      if (other.hasName()) {
        bitField0_ |= 0x00000001;
        name_ = other.name_;
        onChanged();
      }
      internalGetMutableEndpoints().mergeFrom(
          other.internalGetEndpoints());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      tools.elide.meta.AppInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (tools.elide.meta.AppInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object version_ = "";
    /**
     * <pre>
     * Version string of the application.
     * </pre>
     *
     * <code>string version = 1;</code>
     * @return The version.
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Version string of the application.
     * </pre>
     *
     * <code>string version = 1;</code>
     * @return The bytes for version.
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Version string of the application.
     * </pre>
     *
     * <code>string version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Version string of the application.
     * </pre>
     *
     * <code>string version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = getDefaultInstance().getVersion();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Version string of the application.
     * </pre>
     *
     * <code>string version = 1;</code>
     * @param value The bytes for version to set.
     * @return This builder for chaining.
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      version_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * Name of the application, if known.
     * </pre>
     *
     * <code>optional string name = 2;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Name of the application, if known.
     * </pre>
     *
     * <code>optional string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Name of the application, if known.
     * </pre>
     *
     * <code>optional string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Name of the application, if known.
     * </pre>
     *
     * <code>optional string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the application, if known.
     * </pre>
     *
     * <code>optional string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the application, if known.
     * </pre>
     *
     * <code>optional string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, tools.elide.meta.Endpoint> endpoints_;
    private com.google.protobuf.MapField<java.lang.String, tools.elide.meta.Endpoint>
    internalGetEndpoints() {
      if (endpoints_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            EndpointsDefaultEntryHolder.defaultEntry);
      }
      return endpoints_;
    }
    private com.google.protobuf.MapField<java.lang.String, tools.elide.meta.Endpoint>
    internalGetMutableEndpoints() {
      onChanged();;
      if (endpoints_ == null) {
        endpoints_ = com.google.protobuf.MapField.newMapField(
            EndpointsDefaultEntryHolder.defaultEntry);
      }
      if (!endpoints_.isMutable()) {
        endpoints_ = endpoints_.copy();
      }
      return endpoints_;
    }

    public int getEndpointsCount() {
      return internalGetEndpoints().getMap().size();
    }
    /**
     * <pre>
     * Map of endpoint tags to their info payloads for this application.
     * </pre>
     *
     * <code>map&lt;string, .meta.Endpoint&gt; endpoints = 3;</code>
     */

    @java.lang.Override
    public boolean containsEndpoints(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetEndpoints().getMap().containsKey(key);
    }
    /**
     * Use {@link #getEndpointsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, tools.elide.meta.Endpoint> getEndpoints() {
      return getEndpointsMap();
    }
    /**
     * <pre>
     * Map of endpoint tags to their info payloads for this application.
     * </pre>
     *
     * <code>map&lt;string, .meta.Endpoint&gt; endpoints = 3;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, tools.elide.meta.Endpoint> getEndpointsMap() {
      return internalGetEndpoints().getMap();
    }
    /**
     * <pre>
     * Map of endpoint tags to their info payloads for this application.
     * </pre>
     *
     * <code>map&lt;string, .meta.Endpoint&gt; endpoints = 3;</code>
     */
    @java.lang.Override

    public tools.elide.meta.Endpoint getEndpointsOrDefault(
        java.lang.String key,
        tools.elide.meta.Endpoint defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, tools.elide.meta.Endpoint> map =
          internalGetEndpoints().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Map of endpoint tags to their info payloads for this application.
     * </pre>
     *
     * <code>map&lt;string, .meta.Endpoint&gt; endpoints = 3;</code>
     */
    @java.lang.Override

    public tools.elide.meta.Endpoint getEndpointsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, tools.elide.meta.Endpoint> map =
          internalGetEndpoints().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearEndpoints() {
      internalGetMutableEndpoints().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * Map of endpoint tags to their info payloads for this application.
     * </pre>
     *
     * <code>map&lt;string, .meta.Endpoint&gt; endpoints = 3;</code>
     */

    public Builder removeEndpoints(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableEndpoints().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, tools.elide.meta.Endpoint>
    getMutableEndpoints() {
      return internalGetMutableEndpoints().getMutableMap();
    }
    /**
     * <pre>
     * Map of endpoint tags to their info payloads for this application.
     * </pre>
     *
     * <code>map&lt;string, .meta.Endpoint&gt; endpoints = 3;</code>
     */
    public Builder putEndpoints(
        java.lang.String key,
        tools.elide.meta.Endpoint value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableEndpoints().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     * Map of endpoint tags to their info payloads for this application.
     * </pre>
     *
     * <code>map&lt;string, .meta.Endpoint&gt; endpoints = 3;</code>
     */

    public Builder putAllEndpoints(
        java.util.Map<java.lang.String, tools.elide.meta.Endpoint> values) {
      internalGetMutableEndpoints().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:meta.AppInfo)
  }

  // @@protoc_insertion_point(class_scope:meta.AppInfo)
  private static final tools.elide.meta.AppInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new tools.elide.meta.AppInfo();
  }

  public static tools.elide.meta.AppInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AppInfo>
      PARSER = new com.google.protobuf.AbstractParser<AppInfo>() {
    @java.lang.Override
    public AppInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AppInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AppInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AppInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public tools.elide.meta.AppInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

