// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: elide/meta/app.proto

package tools.elide.meta;

/**
 * <pre>
 * Main application manifest for an app powered by Elide; carries info about the build that produced a given app binary,
 * and application configuration.
 * </pre>
 *
 * Protobuf type {@code meta.AppManifest}
 */
public final class AppManifest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:meta.AppManifest)
    AppManifestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AppManifest.newBuilder() to construct.
  private AppManifest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AppManifest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AppManifest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AppManifest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            tools.elide.meta.AppInfo.Builder subBuilder = null;
            if (app_ != null) {
              subBuilder = app_.toBuilder();
            }
            app_ = input.readMessage(tools.elide.meta.AppInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(app_);
              app_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            tools.elide.meta.BuildInfo.Builder subBuilder = null;
            if (build_ != null) {
              subBuilder = build_.toBuilder();
            }
            build_ = input.readMessage(tools.elide.meta.BuildInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(build_);
              build_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return tools.elide.meta.App.internal_static_meta_AppManifest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return tools.elide.meta.App.internal_static_meta_AppManifest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            tools.elide.meta.AppManifest.class, tools.elide.meta.AppManifest.Builder.class);
  }

  public static final int APP_FIELD_NUMBER = 1;
  private tools.elide.meta.AppInfo app_;
  /**
   * <pre>
   * App info/configuration.
   * </pre>
   *
   * <code>.meta.AppInfo app = 1;</code>
   * @return Whether the app field is set.
   */
  @java.lang.Override
  public boolean hasApp() {
    return app_ != null;
  }
  /**
   * <pre>
   * App info/configuration.
   * </pre>
   *
   * <code>.meta.AppInfo app = 1;</code>
   * @return The app.
   */
  @java.lang.Override
  public tools.elide.meta.AppInfo getApp() {
    return app_ == null ? tools.elide.meta.AppInfo.getDefaultInstance() : app_;
  }
  /**
   * <pre>
   * App info/configuration.
   * </pre>
   *
   * <code>.meta.AppInfo app = 1;</code>
   */
  @java.lang.Override
  public tools.elide.meta.AppInfoOrBuilder getAppOrBuilder() {
    return getApp();
  }

  public static final int BUILD_FIELD_NUMBER = 2;
  private tools.elide.meta.BuildInfo build_;
  /**
   * <pre>
   * Build info/configuration.
   * </pre>
   *
   * <code>.meta.BuildInfo build = 2;</code>
   * @return Whether the build field is set.
   */
  @java.lang.Override
  public boolean hasBuild() {
    return build_ != null;
  }
  /**
   * <pre>
   * Build info/configuration.
   * </pre>
   *
   * <code>.meta.BuildInfo build = 2;</code>
   * @return The build.
   */
  @java.lang.Override
  public tools.elide.meta.BuildInfo getBuild() {
    return build_ == null ? tools.elide.meta.BuildInfo.getDefaultInstance() : build_;
  }
  /**
   * <pre>
   * Build info/configuration.
   * </pre>
   *
   * <code>.meta.BuildInfo build = 2;</code>
   */
  @java.lang.Override
  public tools.elide.meta.BuildInfoOrBuilder getBuildOrBuilder() {
    return getBuild();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (app_ != null) {
      output.writeMessage(1, getApp());
    }
    if (build_ != null) {
      output.writeMessage(2, getBuild());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (app_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getApp());
    }
    if (build_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getBuild());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof tools.elide.meta.AppManifest)) {
      return super.equals(obj);
    }
    tools.elide.meta.AppManifest other = (tools.elide.meta.AppManifest) obj;

    if (hasApp() != other.hasApp()) return false;
    if (hasApp()) {
      if (!getApp()
          .equals(other.getApp())) return false;
    }
    if (hasBuild() != other.hasBuild()) return false;
    if (hasBuild()) {
      if (!getBuild()
          .equals(other.getBuild())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasApp()) {
      hash = (37 * hash) + APP_FIELD_NUMBER;
      hash = (53 * hash) + getApp().hashCode();
    }
    if (hasBuild()) {
      hash = (37 * hash) + BUILD_FIELD_NUMBER;
      hash = (53 * hash) + getBuild().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static tools.elide.meta.AppManifest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tools.elide.meta.AppManifest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tools.elide.meta.AppManifest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tools.elide.meta.AppManifest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tools.elide.meta.AppManifest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tools.elide.meta.AppManifest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tools.elide.meta.AppManifest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static tools.elide.meta.AppManifest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static tools.elide.meta.AppManifest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static tools.elide.meta.AppManifest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static tools.elide.meta.AppManifest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static tools.elide.meta.AppManifest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(tools.elide.meta.AppManifest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Main application manifest for an app powered by Elide; carries info about the build that produced a given app binary,
   * and application configuration.
   * </pre>
   *
   * Protobuf type {@code meta.AppManifest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:meta.AppManifest)
      tools.elide.meta.AppManifestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tools.elide.meta.App.internal_static_meta_AppManifest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tools.elide.meta.App.internal_static_meta_AppManifest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tools.elide.meta.AppManifest.class, tools.elide.meta.AppManifest.Builder.class);
    }

    // Construct using tools.elide.meta.AppManifest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (appBuilder_ == null) {
        app_ = null;
      } else {
        app_ = null;
        appBuilder_ = null;
      }
      if (buildBuilder_ == null) {
        build_ = null;
      } else {
        build_ = null;
        buildBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return tools.elide.meta.App.internal_static_meta_AppManifest_descriptor;
    }

    @java.lang.Override
    public tools.elide.meta.AppManifest getDefaultInstanceForType() {
      return tools.elide.meta.AppManifest.getDefaultInstance();
    }

    @java.lang.Override
    public tools.elide.meta.AppManifest build() {
      tools.elide.meta.AppManifest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public tools.elide.meta.AppManifest buildPartial() {
      tools.elide.meta.AppManifest result = new tools.elide.meta.AppManifest(this);
      if (appBuilder_ == null) {
        result.app_ = app_;
      } else {
        result.app_ = appBuilder_.build();
      }
      if (buildBuilder_ == null) {
        result.build_ = build_;
      } else {
        result.build_ = buildBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof tools.elide.meta.AppManifest) {
        return mergeFrom((tools.elide.meta.AppManifest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(tools.elide.meta.AppManifest other) {
      if (other == tools.elide.meta.AppManifest.getDefaultInstance()) return this;
      if (other.hasApp()) {
        mergeApp(other.getApp());
      }
      if (other.hasBuild()) {
        mergeBuild(other.getBuild());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      tools.elide.meta.AppManifest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (tools.elide.meta.AppManifest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private tools.elide.meta.AppInfo app_;
    private com.google.protobuf.SingleFieldBuilderV3<
        tools.elide.meta.AppInfo, tools.elide.meta.AppInfo.Builder, tools.elide.meta.AppInfoOrBuilder> appBuilder_;
    /**
     * <pre>
     * App info/configuration.
     * </pre>
     *
     * <code>.meta.AppInfo app = 1;</code>
     * @return Whether the app field is set.
     */
    public boolean hasApp() {
      return appBuilder_ != null || app_ != null;
    }
    /**
     * <pre>
     * App info/configuration.
     * </pre>
     *
     * <code>.meta.AppInfo app = 1;</code>
     * @return The app.
     */
    public tools.elide.meta.AppInfo getApp() {
      if (appBuilder_ == null) {
        return app_ == null ? tools.elide.meta.AppInfo.getDefaultInstance() : app_;
      } else {
        return appBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * App info/configuration.
     * </pre>
     *
     * <code>.meta.AppInfo app = 1;</code>
     */
    public Builder setApp(tools.elide.meta.AppInfo value) {
      if (appBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        app_ = value;
        onChanged();
      } else {
        appBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * App info/configuration.
     * </pre>
     *
     * <code>.meta.AppInfo app = 1;</code>
     */
    public Builder setApp(
        tools.elide.meta.AppInfo.Builder builderForValue) {
      if (appBuilder_ == null) {
        app_ = builderForValue.build();
        onChanged();
      } else {
        appBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * App info/configuration.
     * </pre>
     *
     * <code>.meta.AppInfo app = 1;</code>
     */
    public Builder mergeApp(tools.elide.meta.AppInfo value) {
      if (appBuilder_ == null) {
        if (app_ != null) {
          app_ =
            tools.elide.meta.AppInfo.newBuilder(app_).mergeFrom(value).buildPartial();
        } else {
          app_ = value;
        }
        onChanged();
      } else {
        appBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * App info/configuration.
     * </pre>
     *
     * <code>.meta.AppInfo app = 1;</code>
     */
    public Builder clearApp() {
      if (appBuilder_ == null) {
        app_ = null;
        onChanged();
      } else {
        app_ = null;
        appBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * App info/configuration.
     * </pre>
     *
     * <code>.meta.AppInfo app = 1;</code>
     */
    public tools.elide.meta.AppInfo.Builder getAppBuilder() {
      
      onChanged();
      return getAppFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * App info/configuration.
     * </pre>
     *
     * <code>.meta.AppInfo app = 1;</code>
     */
    public tools.elide.meta.AppInfoOrBuilder getAppOrBuilder() {
      if (appBuilder_ != null) {
        return appBuilder_.getMessageOrBuilder();
      } else {
        return app_ == null ?
            tools.elide.meta.AppInfo.getDefaultInstance() : app_;
      }
    }
    /**
     * <pre>
     * App info/configuration.
     * </pre>
     *
     * <code>.meta.AppInfo app = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        tools.elide.meta.AppInfo, tools.elide.meta.AppInfo.Builder, tools.elide.meta.AppInfoOrBuilder> 
        getAppFieldBuilder() {
      if (appBuilder_ == null) {
        appBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            tools.elide.meta.AppInfo, tools.elide.meta.AppInfo.Builder, tools.elide.meta.AppInfoOrBuilder>(
                getApp(),
                getParentForChildren(),
                isClean());
        app_ = null;
      }
      return appBuilder_;
    }

    private tools.elide.meta.BuildInfo build_;
    private com.google.protobuf.SingleFieldBuilderV3<
        tools.elide.meta.BuildInfo, tools.elide.meta.BuildInfo.Builder, tools.elide.meta.BuildInfoOrBuilder> buildBuilder_;
    /**
     * <pre>
     * Build info/configuration.
     * </pre>
     *
     * <code>.meta.BuildInfo build = 2;</code>
     * @return Whether the build field is set.
     */
    public boolean hasBuild() {
      return buildBuilder_ != null || build_ != null;
    }
    /**
     * <pre>
     * Build info/configuration.
     * </pre>
     *
     * <code>.meta.BuildInfo build = 2;</code>
     * @return The build.
     */
    public tools.elide.meta.BuildInfo getBuild() {
      if (buildBuilder_ == null) {
        return build_ == null ? tools.elide.meta.BuildInfo.getDefaultInstance() : build_;
      } else {
        return buildBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Build info/configuration.
     * </pre>
     *
     * <code>.meta.BuildInfo build = 2;</code>
     */
    public Builder setBuild(tools.elide.meta.BuildInfo value) {
      if (buildBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        build_ = value;
        onChanged();
      } else {
        buildBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Build info/configuration.
     * </pre>
     *
     * <code>.meta.BuildInfo build = 2;</code>
     */
    public Builder setBuild(
        tools.elide.meta.BuildInfo.Builder builderForValue) {
      if (buildBuilder_ == null) {
        build_ = builderForValue.build();
        onChanged();
      } else {
        buildBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Build info/configuration.
     * </pre>
     *
     * <code>.meta.BuildInfo build = 2;</code>
     */
    public Builder mergeBuild(tools.elide.meta.BuildInfo value) {
      if (buildBuilder_ == null) {
        if (build_ != null) {
          build_ =
            tools.elide.meta.BuildInfo.newBuilder(build_).mergeFrom(value).buildPartial();
        } else {
          build_ = value;
        }
        onChanged();
      } else {
        buildBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Build info/configuration.
     * </pre>
     *
     * <code>.meta.BuildInfo build = 2;</code>
     */
    public Builder clearBuild() {
      if (buildBuilder_ == null) {
        build_ = null;
        onChanged();
      } else {
        build_ = null;
        buildBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Build info/configuration.
     * </pre>
     *
     * <code>.meta.BuildInfo build = 2;</code>
     */
    public tools.elide.meta.BuildInfo.Builder getBuildBuilder() {
      
      onChanged();
      return getBuildFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Build info/configuration.
     * </pre>
     *
     * <code>.meta.BuildInfo build = 2;</code>
     */
    public tools.elide.meta.BuildInfoOrBuilder getBuildOrBuilder() {
      if (buildBuilder_ != null) {
        return buildBuilder_.getMessageOrBuilder();
      } else {
        return build_ == null ?
            tools.elide.meta.BuildInfo.getDefaultInstance() : build_;
      }
    }
    /**
     * <pre>
     * Build info/configuration.
     * </pre>
     *
     * <code>.meta.BuildInfo build = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        tools.elide.meta.BuildInfo, tools.elide.meta.BuildInfo.Builder, tools.elide.meta.BuildInfoOrBuilder> 
        getBuildFieldBuilder() {
      if (buildBuilder_ == null) {
        buildBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            tools.elide.meta.BuildInfo, tools.elide.meta.BuildInfo.Builder, tools.elide.meta.BuildInfoOrBuilder>(
                getBuild(),
                getParentForChildren(),
                isClean());
        build_ = null;
      }
      return buildBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:meta.AppManifest)
  }

  // @@protoc_insertion_point(class_scope:meta.AppManifest)
  private static final tools.elide.meta.AppManifest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new tools.elide.meta.AppManifest();
  }

  public static tools.elide.meta.AppManifest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AppManifest>
      PARSER = new com.google.protobuf.AbstractParser<AppManifest>() {
    @java.lang.Override
    public AppManifest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AppManifest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AppManifest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AppManifest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public tools.elide.meta.AppManifest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

