// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: elide/meta/app.proto

package tools.elide.meta;

public interface EndpointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meta.Endpoint)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Tag generated for an endpoint.
   * </pre>
   *
   * <code>string tag = 1;</code>
   * @return The tag.
   */
  java.lang.String getTag();
  /**
   * <pre>
   * Tag generated for an endpoint.
   * </pre>
   *
   * <code>string tag = 1;</code>
   * @return The bytes for tag.
   */
  com.google.protobuf.ByteString
      getTagBytes();

  /**
   * <pre>
   * Name given to an endpoint, if applicable.
   * </pre>
   *
   * <code>optional string name = 2;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <pre>
   * Name given to an endpoint, if applicable.
   * </pre>
   *
   * <code>optional string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Name given to an endpoint, if applicable.
   * </pre>
   *
   * <code>optional string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Type of endpoint detected or configured for this payload.
   * </pre>
   *
   * <code>.meta.EndpointType type = 3;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <pre>
   * Type of endpoint detected or configured for this payload.
   * </pre>
   *
   * <code>.meta.EndpointType type = 3;</code>
   * @return The type.
   */
  tools.elide.meta.EndpointType getType();

  /**
   * <pre>
   * URL base for this endpoint (controller).
   * </pre>
   *
   * <code>string base = 4;</code>
   * @return The base.
   */
  java.lang.String getBase();
  /**
   * <pre>
   * URL base for this endpoint (controller).
   * </pre>
   *
   * <code>string base = 4;</code>
   * @return The bytes for base.
   */
  com.google.protobuf.ByteString
      getBaseBytes();

  /**
   * <pre>
   * URL tail for this endpoint (method).
   * </pre>
   *
   * <code>optional string tail = 5;</code>
   * @return Whether the tail field is set.
   */
  boolean hasTail();
  /**
   * <pre>
   * URL tail for this endpoint (method).
   * </pre>
   *
   * <code>optional string tail = 5;</code>
   * @return The tail.
   */
  java.lang.String getTail();
  /**
   * <pre>
   * URL tail for this endpoint (method).
   * </pre>
   *
   * <code>optional string tail = 5;</code>
   * @return The bytes for tail.
   */
  com.google.protobuf.ByteString
      getTailBytes();

  /**
   * <pre>
   * Types accepted by this method.
   * </pre>
   *
   * <code>repeated string consumes = 6;</code>
   * @return A list containing the consumes.
   */
  java.util.List<java.lang.String>
      getConsumesList();
  /**
   * <pre>
   * Types accepted by this method.
   * </pre>
   *
   * <code>repeated string consumes = 6;</code>
   * @return The count of consumes.
   */
  int getConsumesCount();
  /**
   * <pre>
   * Types accepted by this method.
   * </pre>
   *
   * <code>repeated string consumes = 6;</code>
   * @param index The index of the element to return.
   * @return The consumes at the given index.
   */
  java.lang.String getConsumes(int index);
  /**
   * <pre>
   * Types accepted by this method.
   * </pre>
   *
   * <code>repeated string consumes = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the consumes at the given index.
   */
  com.google.protobuf.ByteString
      getConsumesBytes(int index);

  /**
   * <pre>
   * Types produced by this method.
   * </pre>
   *
   * <code>repeated string produces = 7;</code>
   * @return A list containing the produces.
   */
  java.util.List<java.lang.String>
      getProducesList();
  /**
   * <pre>
   * Types produced by this method.
   * </pre>
   *
   * <code>repeated string produces = 7;</code>
   * @return The count of produces.
   */
  int getProducesCount();
  /**
   * <pre>
   * Types produced by this method.
   * </pre>
   *
   * <code>repeated string produces = 7;</code>
   * @param index The index of the element to return.
   * @return The produces at the given index.
   */
  java.lang.String getProduces(int index);
  /**
   * <pre>
   * Types produced by this method.
   * </pre>
   *
   * <code>repeated string produces = 7;</code>
   * @param index The index of the value to return.
   * @return The bytes of the produces at the given index.
   */
  com.google.protobuf.ByteString
      getProducesBytes(int index);

  /**
   * <pre>
   * HTTP methods supported by this endpoint.
   * </pre>
   *
   * <code>repeated .meta.EndpointMethods method = 8;</code>
   * @return A list containing the method.
   */
  java.util.List<tools.elide.meta.EndpointMethods> getMethodList();
  /**
   * <pre>
   * HTTP methods supported by this endpoint.
   * </pre>
   *
   * <code>repeated .meta.EndpointMethods method = 8;</code>
   * @return The count of method.
   */
  int getMethodCount();
  /**
   * <pre>
   * HTTP methods supported by this endpoint.
   * </pre>
   *
   * <code>repeated .meta.EndpointMethods method = 8;</code>
   * @param index The index of the element to return.
   * @return The method at the given index.
   */
  tools.elide.meta.EndpointMethods getMethod(int index);
  /**
   * <pre>
   * HTTP methods supported by this endpoint.
   * </pre>
   *
   * <code>repeated .meta.EndpointMethods method = 8;</code>
   * @return A list containing the enum numeric values on the wire for method.
   */
  java.util.List<java.lang.Integer>
  getMethodValueList();
  /**
   * <pre>
   * HTTP methods supported by this endpoint.
   * </pre>
   *
   * <code>repeated .meta.EndpointMethods method = 8;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of method at the given index.
   */
  int getMethodValue(int index);

  /**
   * <pre>
   * Options which apply to this endpoint.
   * </pre>
   *
   * <code>.meta.EndpointOptions options = 9;</code>
   * @return Whether the options field is set.
   */
  boolean hasOptions();
  /**
   * <pre>
   * Options which apply to this endpoint.
   * </pre>
   *
   * <code>.meta.EndpointOptions options = 9;</code>
   * @return The options.
   */
  tools.elide.meta.EndpointOptions getOptions();
  /**
   * <pre>
   * Options which apply to this endpoint.
   * </pre>
   *
   * <code>.meta.EndpointOptions options = 9;</code>
   */
  tools.elide.meta.EndpointOptionsOrBuilder getOptionsOrBuilder();
}
