packages:
  - packages/base
  - packages/core
  - packages/frontend
  - packages/graalvm
  - packages/graalvm-js
  - packages/graalvm-react
  - packages/model
  - packages/rpc
  - packages/test
  - packages/cli
  - site/docs/content
  - tools/scripts

