
#
# Elide: Docker Images
# --------------------
# Image: JVM (v23)
#

IMAGE ?= runtime/jvm23
PROVENANCE ?= yes
PUB_IMAGE ?= runtime-jvm23
REPOSITORY ?= tools/$(IMAGE)
PUB_IMAGE_PATH ?= ghcr.io/elide-dev/runtime/jvm23:$(VERSION)
ORIGIN_IMAGE ?= $(PUB_IMAGE_PATH)

include ../Docker.mk
