steps:
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "run",
      "--rm",
      "--privileged",
      "tonistiigi/binfmt",
      "--install",
      "all"
    ]
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "buildx",
      "create",
      "--name", "multiarch",
      "--driver", "docker-container",
      "--use"
    ]
  - name: "gcr.io/cloud-builders/docker"
    dir: "tools/images/base"
    args: [
      "buildx",
      "build",
      "--push",
      "--platform", "linux/arm64,linux/amd64",
      "--tag", "us-docker.pkg.dev/elide-fw/tools/base",
      "."
    ]
options:
  logging: CLOUD_LOGGING_ONLY
projectId: elide-fw
