
#
# Elide: Docker Images
# --------------------
# Image: Base (Ubuntu)
#

IMAGE ?= base
PUB_IMAGE ?= base
REPOSITORY ?= tools/$(IMAGE)
PUB_IMAGE_PATH ?= ghcr.io/elide-dev/base:$(VERSION)

include ../Docker.mk
