
#
# Elide: Docker Images
# --------------------
# Image: Base (Ubuntu)
#

IMAGE ?= base
PUB_IMAGE ?= base
PROVENANCE ?= yes
REPOSITORY ?= tools/$(IMAGE)
PUB_IMAGE_PATH ?= ghcr.io/elide-dev/base:$(VERSION)
ORIGIN_IMAGE ?= $(PUB_IMAGE_PATH)

include ../Docker.mk
