steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["run", "--rm", "--privileged", "tonistiigi/binfmt", "--install", "all"]
  - name: "gcr.io/cloud-builders/docker"
    dir: "tools/images/codespace"
    args: ["build", "-t", "us-docker.pkg.dev/elide-fw/tools/codespace", "."]
images: ["us-docker.pkg.dev/elide-fw/tools/codespace"]
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_32
projectId: elide-fw
