export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git)
source $ZSH/oh-my-zsh.sh
source ~/.profile
source ~/.alias
if [ -f '/var/lib/gcloud/google-cloud-sdk/path.zsh.inc' ]; then . '/var/lib/gcloud/google-cloud-sdk/path.zsh.inc'; fi
