
#
# Elide: Docker Images
# --------------------
# Image: JDK (v20)
#

IMAGE ?= jdk20
PROVENANCE ?= yes
PUB_IMAGE ?= tools-$(IMAGE)
REPOSITORY ?= tools/$(IMAGE)
PUB_IMAGE_PATH ?= ghcr.io/elide-dev/tools/jdk20
ORIGIN_IMAGE ?= $(PUB_IMAGE_PATH)

include ../Docker.mk
