
#
# Elide: Docker Images
# --------------------
# Image: Base (Alpine)
#

IMAGE ?= base/alpine
PUB_IMAGE ?= base-alpine
REPOSITORY ?= tools/$(IMAGE)
PUB_IMAGE_PATH ?= ghcr.io/elide-dev/base/alpine:$(VERSION)

include ../Docker.mk
