
#
# Elide: Docker Images
# --------------------
# Image: JVM (v20)
#

IMAGE ?= runtime/jvm20
PROVENANCE ?= yes
PUB_IMAGE ?= runtime-jvm20
REPOSITORY ?= tools/$(IMAGE)
PUB_IMAGE_PATH ?= ghcr.io/elide-dev/runtime/jvm20:$(VERSION)
ORIGIN_IMAGE ?= $(PUB_IMAGE_PATH)

include ../Docker.mk
