/*
 * Copyright (c) 2023 Elide Ventures, LLC.
 *
 * Licensed under the MIT license (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 *   https://opensource.org/license/mit/
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under the License.
 */

// automatically generated by the FlatBuffers compiler, do not modify

package elide.base

import com.google.flatbuffers.Constants
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.Table
import java.nio.ByteBuffer
import java.nio.ByteOrder

@Suppress("unused")
class LanguageSpec : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : LanguageSpec {
        __init(_i, _bb)
        return this
    }
    val selection : elide.base.LanguageSpec_.LanguageSelection? get() = selection(elide.base.LanguageSpec_.LanguageSelection())
    fun selection(obj: elide.base.LanguageSpec_.LanguageSelection) : elide.base.LanguageSpec_.LanguageSelection? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val modifier : elide.base.LanguageSpec_.LanguageModifier? get() = modifier(elide.base.LanguageSpec_.LanguageModifier())
    fun modifier(obj: elide.base.LanguageSpec_.LanguageModifier) : elide.base.LanguageSpec_.LanguageModifier? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_22_12_06()
        fun getRootAsLanguageSpec(_bb: ByteBuffer): LanguageSpec = getRootAsLanguageSpec(_bb, LanguageSpec())
        fun getRootAsLanguageSpec(_bb: ByteBuffer, obj: LanguageSpec): LanguageSpec {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createLanguageSpec(builder: FlatBufferBuilder, selectionOffset: Int, modifierOffset: Int) : Int {
            builder.startTable(2)
            addModifier(builder, modifierOffset)
            addSelection(builder, selectionOffset)
            return endLanguageSpec(builder)
        }
        fun startLanguageSpec(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addSelection(builder: FlatBufferBuilder, selection: Int) = builder.addOffset(0, selection, 0)
        fun addModifier(builder: FlatBufferBuilder, modifier: Int) = builder.addOffset(1, modifier, 0)
        fun endLanguageSpec(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
