[versions]
micronaut-core = "4.8.9"
micronaut-context = "4.8.9"
micronaut-platform = "4.7.6"
micronaut-picocli = "5.7.0"
micronaut-graal = "4.8.9"
micronaut-runtime = "4.8.9"
micronaut-inject-kotlin = "4.8.9"
micronaut-test-core = "4.7.0"
micronaut-test-junit5 = "4.7.0"
