[package]
name = "umbrella"
version = "0.1.0"
edition = '2021'
workspace = "../.."
publish = false

[lib]
name = "umbrella"
crate-type = ["lib", "staticlib", "cdylib"]

[features]
default = ["jvm"]
jvm = ["jni/default", "jni/invocation"]
python = ["uv"]
ruby = []
wasm = []
js = ["oxc"]

[lints.rust]
unsafe_code = "warn"
dead_code = "allow"

[dependencies]
boring = "4.6.0"
heapless = "0.8.0"
jni = "0.21.1"
lazy_static = "1.4.0"
oxc = { path = "../../third_party/oxc-project/oxc/crates/oxc", optional = true }
polling = "3.7.0"
ruff = { path = "../../third_party/astral/ruff/crates/ruff", optional = true }
ruff_diagnostics = { path = "../../third_party/astral/ruff/crates/ruff_diagnostics", optional = true }
ruff_formatter = { path = "../../third_party/astral/ruff/crates/ruff_formatter", optional = true }
ruff_linter = { path = "../../third_party/astral/ruff/crates/ruff_linter", optional = true }
rusqlite = { version = "0.31.0", features = ["bundled"] }
serde = { version = "1.0.203", features = ["derive"] }
typeshare = "1.0.3"
uv = { path = "../../third_party/astral/uv/crates/uv", optional = true }
