// automatically generated by the FlatBuffers compiler, do not modify

package elide.page.Context_.AppManifest_

@Suppress("unused")
class DisplayMode private constructor() {
    companion object {
        const val BROWSER: Int = 0
        const val FULLSCREEN: Int = 1
        const val STANDALONE: Int = 2
        const val MINIMALUI: Int = 3
        val names: Array<String> = arrayOf("BROWSER", "FULLSCREEN", "STANDALONE", "MINIMAL_UI")
        fun name(e: Int): String = names[e]
    }
}
