/*
 * Copyright (c) 2023 Elide Ventures, LLC.
 *
 * Licensed under the MIT license (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 *   https://opensource.org/license/mit/
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under the License.
 */

// automatically generated by the FlatBuffers compiler, do not modify

package elide.page.Context_.AppManifest_

@Suppress("unused")
class OrientationMode private constructor() {
    companion object {
        const val UNSPECIFIEDORIENTATION: Int = 0
        const val ANY: Int = 1
        const val NATURAL: Int = 2
        const val LANDSCAPE: Int = 3
        const val PORTRAIT: Int = 4
        val names : Array<String> = arrayOf("UNSPECIFIED_ORIENTATION", "ANY", "NATURAL", "LANDSCAPE", "PORTRAIT")
        fun name(e: Int) : String = names[e]
    }
}
