name = "elide-static-worker"
compatibility_date = "2025-03-14"

routes = [
  { pattern = "static-worker.samples.elide.dev", custom_domain = true },
]

[observability.logs]
enabled = true

[assets]
directory = "./.dev/artifacts/sites/main"
