
#
# Elide: Docker Images
# --------------------
# Image: JVM (v17)
#

IMAGE ?= runtime/jvm17
PROVENANCE ?= yes
PUB_IMAGE ?= runtime-jvm17
REPOSITORY ?= tools/$(IMAGE)
PUB_IMAGE_PATH ?= ghcr.io/elide-dev/runtime/jvm17:$(VERSION)
ORIGIN_IMAGE ?= $(PUB_IMAGE_PATH)

include ../Docker.mk
