
#
# Elide: Docker Images
# --------------------
# Image: JVM (v17)
#

IMAGE ?= runtime/jvm17
PUB_IMAGE ?= runtime-jvm17
REPOSITORY ?= tools/$(IMAGE)
PUB_IMAGE_PATH ?= ghcr.io/elide-dev/runtime/jvm17:$(VERSION)

include ../Docker.mk
