FROM ghcr.io/elide-dev/base:1.0.0-beta7@sha256:48f18ca490ae0f4a0d2dc427594910b0137a2447aa99cbe8dea754fdb1a69c67

LABEL org.opencontainers.image.vendor=Elide
LABEL org.opencontainers.image.title="Elide Base (Native)"
LABEL org.opencontainers.image.description="Base image for native Elide server apps"
LABEL org.opencontainers.image.version=1.0.0-beta7
LABEL org.opencontainers.image.url=https://github.com/elide-dev/elide
LABEL org.opencontainers.image.base.name=ghcr.io/elide-dev/base
LABEL org.opencontainers.image.source=https://github.com/elide-dev/elide/blob/main/tools/images/native/Dockerfile
