
#
# Elide: Docker Images
# ----------------------
# Image: Native
#

IMAGE ?= runtime/native
PUB_IMAGE ?= runtime-native
REPOSITORY ?= tools/$(IMAGE)
PUB_IMAGE_PATH ?= ghcr.io/elide-dev/runtime/native:$(VERSION)

include ../Docker.mk
