
#
# Elide: Docker Images
# ----------------------
# Image: Native
#

IMAGE ?= runtime/native
PROVENANCE ?= yes
PUB_IMAGE ?= runtime-native
REPOSITORY ?= tools/$(IMAGE)
PUB_IMAGE_PATH ?= ghcr.io/elide-dev/runtime/native:$(VERSION)
ORIGIN_IMAGE ?= $(PUB_IMAGE_PATH)

include ../Docker.mk
