/// <reference path="../../../../../types/index.d.ts" />

import { Database } from "elide:sqlite";
import { startServer } from "./server.ts";
import type { DiscoveredDatabase } from "./database.ts";
import config from "./config.ts";

/**
 * Database Studio - Entry Point
 *
 * Serves a JSON API wrapper for SQL queries.
 * Delegates to the server module which handles all HTTP routing and API logic.
 */

export { Database };

// Configuration loaded from config.json (generated by DbStudioCommand.kt)
const { port, databases } = config;

// Start the server with injected configuration
startServer({ port, databases, Database });