// automatically generated by the FlatBuffers compiler, do not modify

package elide.page

@Suppress("unused")
class VideoProvider private constructor() {
    companion object {
        const val PRIVATE: Int = 0
        const val YOUTUBE: Int = 1
        const val VIMEO: Int = 2
        val names : Array<String> = arrayOf("PRIVATE", "YOUTUBE", "VIMEO")
        fun name(e: Int) : String = names[e]
    }
}
