[cache.disk]
dir = "/tmp/.cache/sccache"
size = 7516192768           # 7 GiBytes

[cache.disk.preprocessor_cache_mode]
use_preprocessor_cache_mode = true
file_stat_matches = true
use_ctime_for_stat = true
ignore_time_macros = false
skip_system_headers = false
hash_working_directory = true
