FROM ghcr.io/elide-dev/base/alpine@sha256:e3f188a14438c26fa4eb1ba5a81f9bc377eaf8546510b993511b622ae9814ff1

LABEL org.opencontainers.image.vendor=Elide
LABEL org.opencontainers.image.title="Elide Base (Native/Alpine)"
LABEL org.opencontainers.image.description="Base image for native Elide server apps on Alpine Linux"
LABEL org.opencontainers.image.version=1.0.0-beta3
LABEL org.opencontainers.image.url=https://github.com/elide-dev/elide
LABEL org.opencontainers.image.base.name=ghcr.io/elide-dev/base/alpine
LABEL org.opencontainers.image.source=https://github.com/elide-dev/elide/blob/main/tools/images/native-alpine/Dockerfile
