
#
# Elide: Docker Images
# --------------------
# Image: JDK (v21)
#

IMAGE ?= jdk21
PROVENANCE ?= yes
PUB_IMAGE ?= tools-$(IMAGE)
REPOSITORY ?= tools/$(IMAGE)
PUB_IMAGE_PATH ?= ghcr.io/elide-dev/tools/jdk21
ORIGIN_IMAGE ?= $(PUB_IMAGE_PATH)

include ../Docker.mk
