
#
# Elide: Docker Images
# --------------------
# Image: JVM (v19)
#

IMAGE ?= runtime/jvm19
PUB_IMAGE ?= runtime-jvm19
REPOSITORY ?= tools/$(IMAGE)
PUB_IMAGE_PATH ?= ghcr.io/elide-dev/runtime/jvm19:$(VERSION)

include ../Docker.mk
