
/** Declares common build script versions. */
object Versions {
  const val kotlin = "1.7.0"
  const val kotlinLanguage = "1.7"
  const val kotlinSerialization = "1.3.3"
  const val kotlinxHtml = "0.7.5"
  const val javaLanguage = "11"
  const val micronaut = "3.5.2"
  const val micronautPlugin = "3.4.1"
  const val micronautKotlin = "3.2.2"
  const val micronautGcp = "4.2.0"
  const val micronautGrpc = "3.3.1"
  const val kotlinWrappers = "pre.347"
  const val coroutinesVersion = "1.6.3"
  const val slf4j = "1.7.36"
  const val grpc = "1.46.0"
  const val grpcKotlin = "1.3.0"
  const val protobuf = "3.20.1"
  const val netty = "4.1.72.Final"
  const val tcNative = "2.0.46.Final"
  const val atomicfu = "1.7.0"
  const val atomicfuPlugin = "0.18.0"
  const val benchmarkPlugin = "0.4.2"
  const val koverPlugin = "0.5.1"
  const val graalvm = "22.1.0"
  const val guava = "31.1-jre"
  const val react = "18.2.0"
  const val dockerPlugin = "7.4.0"
  const val kotlinDslPlugin = "2.4.0"
  const val gauthPlugin = "2.1.5"
  const val nodePlugin = "3.3.0"
  const val node = "18.0.0"
  const val nodeDeclarations = "0.0.7"
  const val nodeBuffers = "6.0.3"
  const val nodeStreams = "4.0.0"
  const val nodeUtil = "0.12.4"
  const val esbuild = "0.14.47"
  const val esbuildPluginAlias = "0.2.1"
  const val testLoggerPlugin = "3.2.0"
  const val versionsPlugin = "0.42.0"
  const val logbackClassic = "1.2.11"
}
