
#
# Elide: Docker Images
# --------------------
# Image: JVM (v11)
#

IMAGE ?= runtime/jvm11
PUB_IMAGE ?= runtime-jvm11
REPOSITORY ?= tools/$(IMAGE)
PUB_IMAGE_PATH ?= ghcr.io/elide-dev/runtime/jvm11:$(VERSION)

include ../Docker.mk
