
#
# Elide: Docker Images
# --------------------
# Image: JVM (v21)
#

IMAGE ?= runtime/jvm21
PROVENANCE ?= yes
PUB_IMAGE ?= runtime-jvm21
REPOSITORY ?= tools/$(IMAGE)
PUB_IMAGE_PATH ?= ghcr.io/elide-dev/runtime/jvm21:$(VERSION)
ORIGIN_IMAGE ?= $(PUB_IMAGE_PATH)

include ../Docker.mk
