//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: elide/model/model.proto

package tools.elide.model;

@kotlin.jvm.JvmName("-initializepersistenceOptions")
inline fun persistenceOptions(block: tools.elide.model.PersistenceOptionsKt.Dsl.() -> kotlin.Unit): tools.elide.model.PersistenceOptions =
  tools.elide.model.PersistenceOptionsKt.Dsl._create(tools.elide.model.PersistenceOptions.newBuilder()).apply { block() }._build()
object PersistenceOptionsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: tools.elide.model.PersistenceOptions.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: tools.elide.model.PersistenceOptions.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): tools.elide.model.PersistenceOptions = _builder.build()

    /**
     * <pre>
     * Specifies the storage mode for this entity.
     * </pre>
     *
     * <code>.model.CollectionMode mode = 1;</code>
     */
     var mode: tools.elide.model.CollectionMode
      @JvmName("getMode")
      get() = _builder.getMode()
      @JvmName("setMode")
      set(value) {
        _builder.setMode(value)
      }
    /**
     * <pre>
     * Specifies the storage mode for this entity.
     * </pre>
     *
     * <code>.model.CollectionMode mode = 1;</code>
     */
    fun clearMode() {
      _builder.clearMode()
    }

    /**
     * <pre>
     * Data path for a given message, with items in the URL corresponding to parameters in the item's key path.
     * </pre>
     *
     * <code>string path = 2;</code>
     */
    var path: kotlin.String
      @JvmName("getPath")
      get() = _builder.getPath()
      @JvmName("setPath")
      set(value) {
        _builder.setPath(value)
      }
    /**
     * <pre>
     * Data path for a given message, with items in the URL corresponding to parameters in the item's key path.
     * </pre>
     *
     * <code>string path = 2;</code>
     */
    fun clearPath() {
      _builder.clearPath()
    }

    /**
     * <pre>
     * Name of this item's parent collection, if applicable.
     * </pre>
     *
     * <code>string parent = 3;</code>
     */
    var parent: kotlin.String
      @JvmName("getParent")
      get() = _builder.getParent()
      @JvmName("setParent")
      set(value) {
        _builder.setParent(value)
      }
    /**
     * <pre>
     * Name of this item's parent collection, if applicable.
     * </pre>
     *
     * <code>string parent = 3;</code>
     */
    fun clearParent() {
      _builder.clearParent()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun tools.elide.model.PersistenceOptions.copy(block: tools.elide.model.PersistenceOptionsKt.Dsl.() -> kotlin.Unit): tools.elide.model.PersistenceOptions =
  tools.elide.model.PersistenceOptionsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

