
ARG BASE_IMAGE=gvm17
ARG BASE_VERSION=":latest"
ARG BASE_ARCH="amd64"
ARG BASE_HASH="@sha256:2d25a613ed3764d375557f709f5d02423eae097abae05eaeca073bedcdb49863"

FROM --platform=linux/${BASE_ARCH} us-docker.pkg.dev/elide-fw/tools/${BASE_IMAGE}${BASE_VERSION}${BASE_HASH}
