// automatically generated by the FlatBuffers compiler, do not modify

package elide.meta.JsSettings_

@Suppress("unused")
class JsFeature private constructor() {
    companion object {
        const val FEATUREUNRECOGNIZED: Int = 0
        const val ESM: Int = 1
        const val NPM: Int = 2
        val names: Array<String> = arrayOf("FEATURE_UNRECOGNIZED", "ESM", "NPM")
        fun name(e: Int): String = names[e]
    }
}
