// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webutil/html/types/html.proto

package com.google.common.html.types;

/**
 * <pre>
 * Message containing a sequence of CSS declarations safe to use in style
 * contexts in an HTML document or in DOM APIs.
 * </pre>
 *
 * Protobuf type {@code webutil.html.types.SafeStyleProto}
 */
public final class SafeStyleProto
    extends com.google.protobuf.GeneratedMessageV3
    implements
        // @@protoc_insertion_point(message_implements:webutil.html.types.SafeStyleProto)
        SafeStyleProtoOrBuilder {

    private static final long serialVersionUID = 0L;

    // Use SafeStyleProto.newBuilder() to construct.
    private SafeStyleProto(
        com.google.protobuf.GeneratedMessageV3.Builder<?> builder
    ) {
        super(builder);
    }

    private SafeStyleProto() {
        privateDoNotAccessOrElseSafeStyleWrappedValue_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({ "unused" })
    protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
        return new SafeStyleProto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
        return this.unknownFields;
    }

    private SafeStyleProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry
    ) throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 42:
                        {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            privateDoNotAccessOrElseSafeStyleWrappedValue_ = bs;
                            break;
                        }
                    default:
                        {
                            if (
                                !parseUnknownField(
                                    input,
                                    unknownFields,
                                    extensionRegistry,
                                    tag
                                )
                            ) {
                                done = true;
                            }
                            break;
                        }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e
                .asInvalidProtocolBufferException()
                .setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.google.common.html.types.Html.internal_static_webutil_html_types_SafeStyleProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return com.google.common.html.types.Html.internal_static_webutil_html_types_SafeStyleProto_fieldAccessorTable.ensureFieldAccessorsInitialized(
            com.google.common.html.types.SafeStyleProto.class,
            com.google.common.html.types.SafeStyleProto.Builder.class
        );
    }

    private int bitField0_;
    public static final int PRIVATE_DO_NOT_ACCESS_OR_ELSE_SAFE_STYLE_WRAPPED_VALUE_FIELD_NUMBER =
        5;
    private volatile java.lang.Object privateDoNotAccessOrElseSafeStyleWrappedValue_;

    /**
     * <pre>
     * IMPORTANT: Never set or read this field, even from tests, it is private.
     * See documentation at the top of .proto file for programming language
     * packages with which to create or read this message.
     * </pre>
     *
     * <code>optional string private_do_not_access_or_else_safe_style_wrapped_value = 5;</code>
     * @return Whether the privateDoNotAccessOrElseSafeStyleWrappedValue field is set.
     */
    @java.lang.Override
    public boolean hasPrivateDoNotAccessOrElseSafeStyleWrappedValue() {
        return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <pre>
     * IMPORTANT: Never set or read this field, even from tests, it is private.
     * See documentation at the top of .proto file for programming language
     * packages with which to create or read this message.
     * </pre>
     *
     * <code>optional string private_do_not_access_or_else_safe_style_wrapped_value = 5;</code>
     * @return The privateDoNotAccessOrElseSafeStyleWrappedValue.
     */
    @java.lang.Override
    public java.lang.String getPrivateDoNotAccessOrElseSafeStyleWrappedValue() {
        java.lang.Object ref = privateDoNotAccessOrElseSafeStyleWrappedValue_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
                privateDoNotAccessOrElseSafeStyleWrappedValue_ = s;
            }
            return s;
        }
    }

    /**
     * <pre>
     * IMPORTANT: Never set or read this field, even from tests, it is private.
     * See documentation at the top of .proto file for programming language
     * packages with which to create or read this message.
     * </pre>
     *
     * <code>optional string private_do_not_access_or_else_safe_style_wrapped_value = 5;</code>
     * @return The bytes for privateDoNotAccessOrElseSafeStyleWrappedValue.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPrivateDoNotAccessOrElseSafeStyleWrappedValueBytes() {
        java.lang.Object ref = privateDoNotAccessOrElseSafeStyleWrappedValue_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref
            );
            privateDoNotAccessOrElseSafeStyleWrappedValue_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
        throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
            com.google.protobuf.GeneratedMessageV3.writeString(
                output,
                5,
                privateDoNotAccessOrElseSafeStyleWrappedValue_
            );
        }
        unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
            size +=
                com.google.protobuf.GeneratedMessageV3.computeStringSize(
                    5,
                    privateDoNotAccessOrElseSafeStyleWrappedValue_
                );
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.google.common.html.types.SafeStyleProto)) {
            return super.equals(obj);
        }
        com.google.common.html.types.SafeStyleProto other = (com.google.common.html.types.SafeStyleProto) obj;

        if (
            hasPrivateDoNotAccessOrElseSafeStyleWrappedValue() !=
            other.hasPrivateDoNotAccessOrElseSafeStyleWrappedValue()
        ) return false;
        if (hasPrivateDoNotAccessOrElseSafeStyleWrappedValue()) {
            if (
                !getPrivateDoNotAccessOrElseSafeStyleWrappedValue()
                    .equals(
                        other.getPrivateDoNotAccessOrElseSafeStyleWrappedValue()
                    )
            ) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasPrivateDoNotAccessOrElseSafeStyleWrappedValue()) {
            hash =
                (37 * hash) +
                PRIVATE_DO_NOT_ACCESS_OR_ELSE_SAFE_STYLE_WRAPPED_VALUE_FIELD_NUMBER;
            hash =
                (53 * hash) +
                getPrivateDoNotAccessOrElseSafeStyleWrappedValue().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static com.google.common.html.types.SafeStyleProto parseFrom(
        java.nio.ByteBuffer data
    ) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.google.common.html.types.SafeStyleProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry
    ) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.google.common.html.types.SafeStyleProto parseFrom(
        com.google.protobuf.ByteString data
    ) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.google.common.html.types.SafeStyleProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry
    ) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.google.common.html.types.SafeStyleProto parseFrom(
        byte[] data
    ) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.google.common.html.types.SafeStyleProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry
    ) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.google.common.html.types.SafeStyleProto parseFrom(
        java.io.InputStream input
    ) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
            PARSER,
            input
        );
    }

    public static com.google.common.html.types.SafeStyleProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry
    ) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
            PARSER,
            input,
            extensionRegistry
        );
    }

    public static com.google.common.html.types.SafeStyleProto parseDelimitedFrom(
        java.io.InputStream input
    ) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
            PARSER,
            input
        );
    }

    public static com.google.common.html.types.SafeStyleProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry
    ) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
            PARSER,
            input,
            extensionRegistry
        );
    }

    public static com.google.common.html.types.SafeStyleProto parseFrom(
        com.google.protobuf.CodedInputStream input
    ) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
            PARSER,
            input
        );
    }

    public static com.google.common.html.types.SafeStyleProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry
    ) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
            PARSER,
            input,
            extensionRegistry
        );
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(
        com.google.common.html.types.SafeStyleProto prototype
    ) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder()
            : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent
    ) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * <pre>
     * Message containing a sequence of CSS declarations safe to use in style
     * contexts in an HTML document or in DOM APIs.
     * </pre>
     *
     * Protobuf type {@code webutil.html.types.SafeStyleProto}
     */
    public static final class Builder
        extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
        implements
            // @@protoc_insertion_point(builder_implements:webutil.html.types.SafeStyleProto)
            com.google.common.html.types.SafeStyleProtoOrBuilder {

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.google.common.html.types.Html.internal_static_webutil_html_types_SafeStyleProto_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.google.common.html.types.Html.internal_static_webutil_html_types_SafeStyleProto_fieldAccessorTable.ensureFieldAccessorsInitialized(
                com.google.common.html.types.SafeStyleProto.class,
                com.google.common.html.types.SafeStyleProto.Builder.class
            );
        }

        // Construct using com.google.common.html.types.SafeStyleProto.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent
        ) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
            ) {}
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            privateDoNotAccessOrElseSafeStyleWrappedValue_ = "";
            bitField0_ = (bitField0_ & ~0x00000001);
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return com.google.common.html.types.Html.internal_static_webutil_html_types_SafeStyleProto_descriptor;
        }

        @java.lang.Override
        public com.google.common.html.types.SafeStyleProto getDefaultInstanceForType() {
            return com.google.common.html.types.SafeStyleProto.getDefaultInstance();
        }

        @java.lang.Override
        public com.google.common.html.types.SafeStyleProto build() {
            com.google.common.html.types.SafeStyleProto result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public com.google.common.html.types.SafeStyleProto buildPartial() {
            com.google.common.html.types.SafeStyleProto result = new com.google.common.html.types.SafeStyleProto(
                this
            );
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                to_bitField0_ |= 0x00000001;
            }
            result.privateDoNotAccessOrElseSafeStyleWrappedValue_ =
                privateDoNotAccessOrElseSafeStyleWrappedValue_;
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value
        ) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field
        ) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof
        ) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index,
            java.lang.Object value
        ) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value
        ) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.google.common.html.types.SafeStyleProto) {
                return mergeFrom(
                    (com.google.common.html.types.SafeStyleProto) other
                );
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(
            com.google.common.html.types.SafeStyleProto other
        ) {
            if (
                other ==
                com.google.common.html.types.SafeStyleProto.getDefaultInstance()
            ) return this;
            if (other.hasPrivateDoNotAccessOrElseSafeStyleWrappedValue()) {
                bitField0_ |= 0x00000001;
                privateDoNotAccessOrElseSafeStyleWrappedValue_ =
                    other.privateDoNotAccessOrElseSafeStyleWrappedValue_;
                onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry
        ) throws java.io.IOException {
            com.google.common.html.types.SafeStyleProto parsedMessage = null;
            try {
                parsedMessage =
                    PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage =
                    (com.google.common.html.types.SafeStyleProto) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private int bitField0_;

        private java.lang.Object privateDoNotAccessOrElseSafeStyleWrappedValue_ =
            "";

        /**
         * <pre>
         * IMPORTANT: Never set or read this field, even from tests, it is private.
         * See documentation at the top of .proto file for programming language
         * packages with which to create or read this message.
         * </pre>
         *
         * <code>optional string private_do_not_access_or_else_safe_style_wrapped_value = 5;</code>
         * @return Whether the privateDoNotAccessOrElseSafeStyleWrappedValue field is set.
         */
        public boolean hasPrivateDoNotAccessOrElseSafeStyleWrappedValue() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <pre>
         * IMPORTANT: Never set or read this field, even from tests, it is private.
         * See documentation at the top of .proto file for programming language
         * packages with which to create or read this message.
         * </pre>
         *
         * <code>optional string private_do_not_access_or_else_safe_style_wrapped_value = 5;</code>
         * @return The privateDoNotAccessOrElseSafeStyleWrappedValue.
         */
        public java.lang.String getPrivateDoNotAccessOrElseSafeStyleWrappedValue() {
            java.lang.Object ref =
                privateDoNotAccessOrElseSafeStyleWrappedValue_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    privateDoNotAccessOrElseSafeStyleWrappedValue_ = s;
                }
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <pre>
         * IMPORTANT: Never set or read this field, even from tests, it is private.
         * See documentation at the top of .proto file for programming language
         * packages with which to create or read this message.
         * </pre>
         *
         * <code>optional string private_do_not_access_or_else_safe_style_wrapped_value = 5;</code>
         * @return The bytes for privateDoNotAccessOrElseSafeStyleWrappedValue.
         */
        public com.google.protobuf.ByteString getPrivateDoNotAccessOrElseSafeStyleWrappedValueBytes() {
            java.lang.Object ref =
                privateDoNotAccessOrElseSafeStyleWrappedValue_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref
                );
                privateDoNotAccessOrElseSafeStyleWrappedValue_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * IMPORTANT: Never set or read this field, even from tests, it is private.
         * See documentation at the top of .proto file for programming language
         * packages with which to create or read this message.
         * </pre>
         *
         * <code>optional string private_do_not_access_or_else_safe_style_wrapped_value = 5;</code>
         * @param value The privateDoNotAccessOrElseSafeStyleWrappedValue to set.
         * @return This builder for chaining.
         */
        public Builder setPrivateDoNotAccessOrElseSafeStyleWrappedValue(
            java.lang.String value
        ) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000001;
            privateDoNotAccessOrElseSafeStyleWrappedValue_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * IMPORTANT: Never set or read this field, even from tests, it is private.
         * See documentation at the top of .proto file for programming language
         * packages with which to create or read this message.
         * </pre>
         *
         * <code>optional string private_do_not_access_or_else_safe_style_wrapped_value = 5;</code>
         * @return This builder for chaining.
         */
        public Builder clearPrivateDoNotAccessOrElseSafeStyleWrappedValue() {
            bitField0_ = (bitField0_ & ~0x00000001);
            privateDoNotAccessOrElseSafeStyleWrappedValue_ =
                getDefaultInstance()
                    .getPrivateDoNotAccessOrElseSafeStyleWrappedValue();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * IMPORTANT: Never set or read this field, even from tests, it is private.
         * See documentation at the top of .proto file for programming language
         * packages with which to create or read this message.
         * </pre>
         *
         * <code>optional string private_do_not_access_or_else_safe_style_wrapped_value = 5;</code>
         * @param value The bytes for privateDoNotAccessOrElseSafeStyleWrappedValue to set.
         * @return This builder for chaining.
         */
        public Builder setPrivateDoNotAccessOrElseSafeStyleWrappedValueBytes(
            com.google.protobuf.ByteString value
        ) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000001;
            privateDoNotAccessOrElseSafeStyleWrappedValue_ = value;
            onChanged();
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields
        ) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields
        ) {
            return super.mergeUnknownFields(unknownFields);
        }
        // @@protoc_insertion_point(builder_scope:webutil.html.types.SafeStyleProto)
    }

    // @@protoc_insertion_point(class_scope:webutil.html.types.SafeStyleProto)
    private static final com.google.common.html.types.SafeStyleProto DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new com.google.common.html.types.SafeStyleProto();
    }

    public static com.google.common.html.types.SafeStyleProto getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated
    public static final com.google.protobuf.Parser<SafeStyleProto> PARSER = new com.google.protobuf.AbstractParser<SafeStyleProto>() {
        @java.lang.Override
        public SafeStyleProto parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry
        ) throws com.google.protobuf.InvalidProtocolBufferException {
            return new SafeStyleProto(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<SafeStyleProto> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SafeStyleProto> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.common.html.types.SafeStyleProto getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }
}
