// automatically generated by the FlatBuffers compiler, do not modify

package webutil.html.types

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

@Suppress("unused")
class SafeStyleProto : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : SafeStyleProto {
        __init(_i, _bb)
        return this
    }
    val privateDoNotAccessOrElseSafeStyleWrappedValue : String?
        get() {
            val o = __offset(4)
            return if (o != 0) __string(o + bb_pos) else null
        }
    val privateDoNotAccessOrElseSafeStyleWrappedValueAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun privateDoNotAccessOrElseSafeStyleWrappedValueInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_22_12_06()
        fun getRootAsSafeStyleProto(_bb: ByteBuffer): SafeStyleProto = getRootAsSafeStyleProto(_bb, SafeStyleProto())
        fun getRootAsSafeStyleProto(_bb: ByteBuffer, obj: SafeStyleProto): SafeStyleProto {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createSafeStyleProto(builder: FlatBufferBuilder, privateDoNotAccessOrElseSafeStyleWrappedValueOffset: Int) : Int {
            builder.startTable(1)
            addPrivateDoNotAccessOrElseSafeStyleWrappedValue(builder, privateDoNotAccessOrElseSafeStyleWrappedValueOffset)
            return endSafeStyleProto(builder)
        }
        fun startSafeStyleProto(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addPrivateDoNotAccessOrElseSafeStyleWrappedValue(builder: FlatBufferBuilder, privateDoNotAccessOrElseSafeStyleWrappedValue: Int) = builder.addOffset(0, privateDoNotAccessOrElseSafeStyleWrappedValue, 0)
        fun endSafeStyleProto(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
