// automatically generated by the FlatBuffers compiler, do not modify

package elide.page.Context_.AppManifest_.RelatedApplication_

@Suppress("unused")
class AppPlatform private constructor() {
    companion object {
        const val UNSPECIFIEDAPPPLATFORM: Int = 0
        const val APPSTORE: Int = 1
        const val PLAYSTORE: Int = 2
        const val WEB: Int = 3
        val names : Array<String> = arrayOf("UNSPECIFIED_APP_PLATFORM", "APPSTORE", "PLAYSTORE", "WEB")
        fun name(e: Int) : String = names[e]
    }
}
