// automatically generated by the FlatBuffers compiler, do not modify

package elide.assets.AssetBundle_.ScriptBundle_

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

@Suppress("unused")
class ScriptAsset : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ScriptAsset {
        __init(_i, _bb)
        return this
    }
    val token : String?
        get() {
            val o = __offset(4)
            return if (o != 0) __string(o + bb_pos) else null
        }
    val tokenAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun tokenInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val filename : String?
        get() {
            val o = __offset(6)
            return if (o != 0) __string(o + bb_pos) else null
        }
    val filenameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun filenameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val script : elide.page.Context_.Scripts_.JavaScript? get() = script(elide.page.Context_.Scripts_.JavaScript())
    fun script(obj: elide.page.Context_.Scripts_.JavaScript) : elide.page.Context_.Scripts_.JavaScript? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_22_12_06()
        fun getRootAsScriptAsset(_bb: ByteBuffer): ScriptAsset = getRootAsScriptAsset(_bb, ScriptAsset())
        fun getRootAsScriptAsset(_bb: ByteBuffer, obj: ScriptAsset): ScriptAsset {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createScriptAsset(builder: FlatBufferBuilder, tokenOffset: Int, filenameOffset: Int, scriptOffset: Int) : Int {
            builder.startTable(3)
            addScript(builder, scriptOffset)
            addFilename(builder, filenameOffset)
            addToken(builder, tokenOffset)
            return endScriptAsset(builder)
        }
        fun startScriptAsset(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addToken(builder: FlatBufferBuilder, token: Int) = builder.addOffset(0, token, 0)
        fun addFilename(builder: FlatBufferBuilder, filename: Int) = builder.addOffset(1, filename, 0)
        fun addScript(builder: FlatBufferBuilder, script: Int) = builder.addOffset(2, script, 0)
        fun endScriptAsset(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
