
ARG BASE_ARCH=amd64

FROM --platform=linux/${BASE_ARCH} gcr.io/distroless/base@sha256:2eb6d15c45d0d35ea270a53b49e93b5f5299d2086a9bcad26da077fa9ed549c5

LABEL org.opencontainers.image.vendor=Elide
LABEL org.opencontainers.image.title="Elide Base (Native)"
LABEL org.opencontainers.image.description="Base image for native Elide server apps"
LABEL org.opencontainers.image.version=v3-alpha1
LABEL org.opencontainers.image.url=https://github.com/elide-dev/v3
LABEL org.opencontainers.image.base.name=gcr.io/distroless/base
LABEL org.opencontainers.image.source=https://github.com/elide-dev/v3/blob/v3/images/native/Dockerfile
