-libraryjars <java.home>/jmods/java.base.jmod(!**.jar)
-libraryjars <java.home>/jmods/java.logging.jmod(!**.jar)
-libraryjars <java.home>/jmods/java.net.http.jmod(!**.jar)
-allowaccessmodification
-optimizeaggressively
-optimizationpasses 10
-dontobfuscate
