// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: elide/model/model.proto

package tools.elide.model;

public interface BigQueryOptionsOrBuilder
    extends
        // @@protoc_insertion_point(interface_extends:model.BigQueryOptions)
        com.google.protobuf.MessageOrBuilder {}
