// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: elide/model/model.proto

package tools.elide.model;

public interface TableFieldOptionsOrBuilder
    extends
        // @@protoc_insertion_point(interface_extends:model.TableFieldOptions)
        com.google.protobuf.MessageOrBuilder {
    /**
     * <pre>
     * Marks this field as `REQUIRED` in tabular schemas.
     * </pre>
     *
     * <code>bool require = 1;</code>
     * @return The require.
     */
    boolean getRequire();

    /**
     * <pre>
     * Marks this field as ignored for serialization in tabular circumstances.
     * </pre>
     *
     * <code>bool ignore = 2;</code>
     * @return The ignore.
     */
    boolean getIgnore();

    /**
     * <pre>
     * Overrides the BigQuery type associated with the exported form of this message field.
     * </pre>
     *
     * <code>.model.BigQueryOptions.BigQueryType bqtype = 3;</code>
     * @return The enum numeric value on the wire for bqtype.
     */
    int getBqtypeValue();
    /**
     * <pre>
     * Overrides the BigQuery type associated with the exported form of this message field.
     * </pre>
     *
     * <code>.model.BigQueryOptions.BigQueryType bqtype = 3;</code>
     * @return The bqtype.
     */
    tools.elide.model.BigQueryOptions.BigQueryType getBqtype();

    /**
     * <pre>
     * Overrides the Spanner type associated with the exported form of this message field.
     * </pre>
     *
     * <code>.model.SpannerOptions.SpannerType sptype = 4;</code>
     * @return The enum numeric value on the wire for sptype.
     */
    int getSptypeValue();
    /**
     * <pre>
     * Overrides the Spanner type associated with the exported form of this message field.
     * </pre>
     *
     * <code>.model.SpannerOptions.SpannerType sptype = 4;</code>
     * @return The sptype.
     */
    tools.elide.model.SpannerOptions.SpannerType getSptype();

    /**
     * <pre>
     * Converts this field into a `REPEATED`-mode field in BigQuery.
     * </pre>
     *
     * <code>bool repeated = 5;</code>
     * @return The repeated.
     */
    boolean getRepeated();

    /**
     * <pre>
     * Size of the field. Pass `0` (the default) for maximum width.
     * </pre>
     *
     * <code>uint32 size = 6;</code>
     * @return The size.
     */
    int getSize();

    /**
     * <pre>
     * Name of the field in columnar circumstances.
     * </pre>
     *
     * <code>string name = 7;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     * Name of the field in columnar circumstances.
     * </pre>
     *
     * <code>string name = 7;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString getNameBytes();

    /**
     * <pre>
     * Unique ID or path assigned to this field in a universally specified data model.
     * </pre>
     *
     * <code>string id = 8;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <pre>
     * Unique ID or path assigned to this field in a universally specified data model.
     * </pre>
     *
     * <code>string id = 8;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString getIdBytes();
}
